site_name: Percona Monitoring and Management Documentation
site_url: https://www.percona.com/doc/percona-monitoring-and-management/2.x
repo_name: percona/pmm-doc
repo_url: https://github.com/percona/pmm-doc
edit_uri: edit/master/docs/
site_description: Percona Monitoring and Management Documentation
site_author: Percona LLC
copyright: Percona LLC, &#169; 2020
use_directory_urls: false
docs_dir: docs

theme:
  name: material
#  custom_dir: theme
  language: en
  palette:
    primary: deep-orange
    accent: white
  font:
    text: Chivo
    code: Roboto Mono
  logo: _images/pmm-doc-logo.svg
  favicon: _images/percona_favicon.ico
#  features:
#     tabs: true # top row navigation bar

extra_css:
    - css/basic.css
    - _static/pygments.css

markdown_extensions:
    - toc:
        baselevel: 1
        toc_depth: "2-3"
        anchorlink: True
#        permalink: 
    - admonition
    - def_list
    - smarty:
        smart_angled_quotes: True
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tabbed
    - pymdownx.tilde
    - pymdownx.superfences
    - pymdownx.highlight:
        linenums: false

plugins:
    - search
    - macros

extra:
    project: 'Percona Monitoring and Management'
    shorttitle: 'Percona Monitoring and Management Documentation'
    copyright: 'Percona LLC and/or its affiliates 2009-2020'
    release: '2.11.1'
    version: '2.11'
    major: '2.x' # Used by version switcher. Should match publish url suffix and site_url
    quickstart: 'https://www.percona.com/software/pmm/quickstart'

nav:
    - Welcome: index.md
    - Setting up:
        - setting-up/index.md
        - Server:
            - setting-up/server/docker.md
            - setting-up/server/virtual-appliance.md
            - setting-up/server/aws.md
            - setting-up/server/verify.md
        - Client:
            - setting-up/client/index.md
            - setting-up/client/mysql.md
            - setting-up/client/percona-server.md
            - setting-up/client/mongodb.md
            - setting-up/client/postgres.md
            - setting-up/client/proxysql.md
            - setting-up/client/aws.md
            - setting-up/client/linux.md
            - setting-up/client/external.md
    - Using:
        - using/index.md
        - using/interface.md
        - using/query-analytics.md
        - Percona Platform:
            - using/platform/intro.md
            - using/platform/stt.md
    - How to:
        - how-to/index.md
        - how-to/update.md
        - how-to/security.md
        - how-to/optimize.md
        - how-to/configure.md
    - Reference:
        - reference/index.md
        - reference/dashboards/index.md
        - Commands:
            - reference/commands/pmm-admin.md
        - reference/api.md
        - reference/glossary.md
    - faq.md
    - 'Release Notes': '/release-notes/'
